development:
  adapter: mysql2
  host: 127.0.0.1
  database: chronopuncture
  username: root
  password:

production:
  <<: *default
  database: chrhonopuncture_production
  username: chrhonopuncture
  password: <%= ENV['CHRHONOPUNCTURE_DATABASE_PASSWORD'] %>