development:
  adapter: mysql2
  host: 127.0.0.1
  database: chronopuncture
  username: root
  password:

production:
  adapter: mysql2
  database: chronopuncture_production
  username: root
  password:

