# development:
#   adapter: mysql2
#   host: 127.0.0.1
#   database: chronopuncture
#   username: root
#   password:

# production:
#   adapter: mysql2
#   database: chronopuncture_production
#   pool: 5
#   username: root
#   password:


default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
 development:
  <<: *default
  database: chronopuncture_development


production:
   <<: *default
  database: chronopuncture_production
  username: chronopuncture
  password: <%= ENV['CHRONOPUNCTURE_DATABASE_PASSWORD'] %>