# development:
#   adapter: mysql2
#   host: 127.0.0.1
#   database: chronopuncture
#   username: root
#   password:

# production:
#   adapter: mysql2
#   database: chronopuncture_production
#   pool: 5
#   username: root
#   password:


development:
  adapter: postgresql
  host: localhost
  username: nick
  database: chronopuncture
  pool: 5


production:
  adapter: postgresql
  database: chronopuncture_production
